# Shadowrocket: 2026-04-21 20:23:18
[General]
bypass-system = true
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, e.crashlytics.com, captive.apple.com
bypass-tun = 10.0.0.0/8,100.64.0.0/10,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.0.0.0/24,192.0.2.0/24,192.88.99.0/24,192.168.0.0/16,198.18.0.0/15,198.51.100.0/24,203.0.113.0/24,224.0.0.0/4,255.255.255.255/32
dns-server = system, 114.114.114.114, 112.124.47.27, 8.8.8.8, 8.8.4.4
update-url = https://h2y.github.io/Shadowrocket-ADBlock-Rules/sr_cnip.conf

[Proxy Group]
UK_SELECT = select,🇬🇧 英国 02,use=true

[Rule]
DOMAIN-SUFFIX,byapis.com,UK_SELECT
DOMAIN-SUFFIX,bytick.com,UK_SELECT
DOMAIN-SUFFIX,bybit.com,UK_SELECT
DOMAIN-KEYWORD,bytick,UK_SELECT
DOMAIN-KEYWORD,bybit,UK_SELECT
RULE-SET,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Shadowrocket/Netflix/Netflix.list,UK_SELECT
#
# 国内外划分，对中国网站直连，外国网站代理。
#
# 不包含广告过滤
#

DOMAIN-SUFFIX,ampproject.org,PROXY //  Google AMP issue#237
GEOIP,CN,DIRECT
FINAL,PROXY

[URL Rewrite]
^http://(www.)?google.cn https://www.google.com 302

# By Moshel @ https://hzy.pw/
